import { motion } from "framer-motion";
import { Brain, Code, MessageSquare, Zap, BookOpen, BarChart3 } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI Learning Paths",
    desc: "Personalized curricula generated by AI, adapting in real-time to your skill level and pace.",
  },
  {
    icon: Code,
    title: "Interactive Code Labs",
    desc: "Hands-on coding environments with instant AI feedback and intelligent error explanations.",
  },
  {
    icon: MessageSquare,
    title: "AI Tutor Chat",
    desc: "24/7 conversational AI tutor that understands context and guides you through complex topics.",
  },
  {
    icon: Zap,
    title: "Smart Assessments",
    desc: "Adaptive quizzes that identify knowledge gaps and reinforce learning through spaced repetition.",
  },
  {
    icon: BookOpen,
    title: "Rich Content Library",
    desc: "Curated resources, tutorials, and documentation woven into your personalized learning journey.",
  },
  {
    icon: BarChart3,
    title: "Progress Analytics",
    desc: "Detailed insights into your learning patterns, strengths, and areas for improvement.",
  },
];

const FeaturesSection = () => (
  <section id="features" className="relative px-6 py-28">
    <div className="mx-auto max-w-6xl">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6 }}
        className="mb-16 text-center"
      >
        <p className="mb-2 font-mono-code text-xs uppercase tracking-[0.3em] text-primary">
          Deep Dive
        </p>
        <h2 className="font-display text-4xl font-bold sm:text-5xl">
          Platform <span className="italic text-gradient-red">Features</span>
        </h2>
      </motion.div>

      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {features.map((f, i) => (
          <motion.div
            key={f.title}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: i * 0.08 }}
            className="glass-card group p-6 transition-all hover:border-primary/40"
          >
            <f.icon className="h-8 w-8 text-primary transition-transform group-hover:scale-110" />
            <h3 className="mt-4 font-display text-lg font-bold">{f.title}</h3>
            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              {f.desc}
            </p>
          </motion.div>
        ))}
      </div>
    </div>
  </section>
);

export default FeaturesSection;
